# Base configs
baseurl: "https://maverickcasanova.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
#google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Saket Sinha"
subtitle: "Ramblings by an Evangelist!"
author: "Maverick"
header:
 title: "Photography"
 subtitle: "by Maverick"
footer:
 name: "Hey there, my name is Maverick"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/ramswaroop/photography\">fork me on github</a> ;)"
web_design: "AJ"
social_urls:
  #facebook: "https://www.facebook.com/saket.sinha.336"
  #twitter: "https://www.twitter.com/ram__patra"
  #instagram: "https://www.instagram.com/saket.sinha34"
  #dribbble: "https://dribbble.com/rampatra"
  #linkedin: "https://in.linkedin.com/in/ram-patra"
  github: "https://www.github.com/maverickcasanova"
